### ISSUE TITLE
bg color

### ISSUE THREAD

**Issue by wnqng** [CramBL/fastPASTA#2]
Hello there,

I was just going through your diagrams and I noticed this background colour that is not in line with my expectations.

Please change it! I think 99.9% of the internet would agree with me.

Thank you in advance.

**Comment by wnqng** [comment]
PS ChatGPT agrees with me.

**Comment by CramBL** [comment]
Hi @wnqng,

If chatGPT agrees then I will definitely consider a new background color. 

Thank you for reporting this issue.
